[package]
name = "kvmi"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"
repository = "https://github.com/Wenzel/kvmi"
readme = "README.md"
keywords = ["KVM", "KVMi"]
description = "Rust bindings for KVMi"
license = "GPL-3.0-only"

[dependencies]
log = "0.4.8"
kvmi-sys = { git = "https://github.com/Wenzel/kvmi-sys.git" }
enum-primitive-derive = "0.1.2"
num-traits = "0.2.8"
nix = "0.16.1"
libc = "0.2.66"