name: KVMi CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install libkvmi
      run: |
        git clone https://github.com/KVM-VMI/kvm --branch kvmi --depth 1
        cd kvm/tools/kvm/kvmi
        make
        sudo make install
    - name: install clippy
      run: rustup component add clippy
    - uses: actions/checkout@v1
    - name: build KVMi
      run: cargo build
    - name: clippy check
      run: cargo clippy -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: install rustfmt
      run: rustup component add rustfmt
    - uses: actions/checkout@v1
    - name: rustfmt check
      run: cargo fmt -- --check
