name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone libkvmi
        uses: actions/checkout@v2
        with:
          repository: bitdefender/libkvmi
          path: libkvmi
          ref: kvmi-v6

      - name: build and install libkvmi
        run: |
          ./bootstrap
          ./configure
          make
          sudo make install
        working-directory: libkvmi

      - name: install stable toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions/checkout@v1
      - name: build KVMi
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: install stable toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - uses: actions/checkout@v1
    - name: rustfmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
