name: Build

on: [push]

jobs:
  kvm:
    runs-on: ubuntu-latest

    steps:
    - name: install libkvmi
      run: |
        git clone https://github.com/KVM-VMI/kvm --branch kvmi --depth 1
        cd kvm/tools/kvm/kvmi
        make
        sudo cp -rv include/ /usr/local
        sudo cp libkvmi.so /usr/local/lib
    - uses: actions/checkout@v1
    - name: build KVM driver
      run: cargo build
