name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install libkvmi
      run: |
        git clone https://github.com/KVM-VMI/kvm --branch kvmi --depth 1
        cd kvm/tools/kvm/kvmi
        make
        sudo make install
    - name: install stable toolchain with clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    - uses: actions/checkout@v1
    - name: build KVMi
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: annotate commit with clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: install stable toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - uses: actions/checkout@v1
    - name: rustfmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
